- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python3-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - hacking-integration-nova:
            voting: false
        - openstack-tox-py312:
            voting: true
    gate:
      jobs:
        - openstack-tox-py312:
            voting: true

- job:
    name: hacking-integration-nova
    parent: openstack-tox
    description: |
      Run the integration job against nova with proposed hacking change.
    required-projects:
      - openstack/nova
    vars:
      tox_envlist: integration
      tox_extra_args: -- openstack nova {{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/nova'].src_dir }}
