- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-pypy-jobs-nonvoting
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints
        - hacking-integration-nova:
            voting: false
    gate:
      jobs:
        - openstack-tox-lower-constraints

    post:
      jobs:
        - openstack-tox-cover
- job:
    name: hacking-integration-nova
    parent: openstack-tox
    description: |
      Run the integration job against nova with proposed hacking change.
    required-projects:
      - openstack/nova
    vars:
      tox_envlist: integration
      tox_extra_args: -vv openstack nova {{ ansible_user_dir }}/{{ zuul.projects['git.openstack.org/openstack/nova'].src_dir }}
